// PyLingo course data.
// Exercise types:
//   mc      — multiple choice { prompt, code?, choices: [], answer: index, explain }
//   type    — typed answer    { prompt, code?, answer: string | [accepted...], explain }
//   arrange — word bank       { prompt, tokens: [], answer: "joined with space", explain }

const COURSE = [
  {
    title: "Unit 1 · First Steps",
    subtitle: "print, comments and your first program",
    color: "",
    lessons: [
      {
        title: "Hello, Python!",
        icon: "👋",
        exercises: [
          { type: "mc", prompt: "Which function displays text on the screen?",
            choices: ["<code>echo()</code>", "<code>print()</code>", "<code>display()</code>", "<code>show()</code>"],
            answer: 1, explain: "print() writes output to the screen." },
          { type: "arrange", prompt: "Build the code: print the text Hello",
            tokens: ["print", "(", '"Hello"', ")"],
            answer: 'print ( "Hello" )', explain: 'print("Hello")' },
          { type: "mc", prompt: "What does this program output?",
            code: 'print("Python is fun")',
            choices: ["Python is fun", '"Python is fun"', "print", "Nothing"],
            answer: 0, explain: "The quotes are not printed — only the text inside them." },
          { type: "type", prompt: "Type the code to print the word cat (use double quotes)",
            answer: ['print("cat")', "print('cat')"], explain: 'print("cat")' },
          { type: "mc", prompt: "Which symbol starts a comment in Python?",
            choices: ["//", "#", "/*", "--"],
            answer: 1, explain: "# starts a comment. Python ignores everything after it on that line." },
          { type: "mc", prompt: "What does this program output?",
            code: '# print("A")\nprint("B")',
            choices: ["A", "B", "A then B", "Nothing"],
            answer: 1, explain: "The first line is a comment, so only B is printed." },
        ],
      },
      {
        title: "Printing more",
        icon: "🖨️",
        exercises: [
          { type: "mc", prompt: "What does this output?",
            code: 'print("Hi")\nprint("there")',
            choices: ["Hi there (same line)", "Hi then there (two lines)", "Hithere", "An error"],
            answer: 1, explain: "Each print() call ends with a new line by default." },
          { type: "arrange", prompt: "Build the code: print the number 42 (no quotes needed)",
            tokens: ["print", "(", "42", ")"],
            answer: "print ( 42 )", explain: "Numbers don't need quotes: print(42)" },
          { type: "mc", prompt: "What does this output?",
            code: 'print("2 + 3")',
            choices: ["5", "2 + 3", "23", "An error"],
            answer: 1, explain: "Text in quotes is printed as-is — the math is not calculated." },
          { type: "mc", prompt: "What does this output?",
            code: "print(2 + 3)",
            choices: ["5", "2 + 3", "2 3", "An error"],
            answer: 0, explain: "Without quotes, Python calculates 2 + 3 first." },
          { type: "type", prompt: "Type the code to print the result of 10 times 5 (use *)",
            answer: ["print(10 * 5)", "print(10*5)", "print(5 * 10)", "print(5*10)"], explain: "print(10 * 5) outputs 50" },
          { type: "mc", prompt: "Which of these will cause an error?",
            choices: ['<code>print("hello")</code>', "<code>print(123)</code>", "<code>print(hello)</code>", '<code>print("123")</code>'],
            answer: 2, explain: "hello without quotes is treated as a variable name — and it was never defined." },
        ],
      },
    ],
  },
  {
    title: "Unit 2 · Variables",
    subtitle: "storing and using data",
    color: "u-blue",
    lessons: [
      {
        title: "Creating variables",
        icon: "📦",
        exercises: [
          { type: "mc", prompt: "How do you create a variable called age with the value 12?",
            choices: ["<code>age == 12</code>", "<code>age = 12</code>", "<code>var age = 12</code>", "<code>12 = age</code>"],
            answer: 1, explain: "A single = assigns a value to a variable." },
          { type: "arrange", prompt: "Build the code: store \"Ana\" in a variable called name",
            tokens: ["name", "=", '"Ana"'],
            answer: 'name = "Ana"', explain: 'name = "Ana"' },
          { type: "mc", prompt: "What does this output?",
            code: 'x = 7\nprint(x)',
            choices: ["x", "7", '"x"', "An error"],
            answer: 1, explain: "print(x) prints the value stored in x." },
          { type: "mc", prompt: "What does this output?",
            code: "score = 10\nscore = 20\nprint(score)",
            choices: ["10", "20", "10 20", "30"],
            answer: 1, explain: "A variable keeps only its most recent value." },
          { type: "type", prompt: "Create a variable called city with the value \"Paris\"",
            answer: ['city = "Paris"', "city = 'Paris'", 'city="Paris"', "city='Paris'"], explain: 'city = "Paris"' },
          { type: "mc", prompt: "Which is a valid variable name?",
            choices: ["<code>2cool</code>", "<code>my-name</code>", "<code>my_name</code>", "<code>my name</code>"],
            answer: 2, explain: "Variable names can't start with a digit or contain spaces/hyphens. Underscores are fine." },
        ],
      },
      {
        title: "Working with variables",
        icon: "🔧",
        exercises: [
          { type: "mc", prompt: "What does this output?",
            code: "a = 5\nb = 3\nprint(a + b)",
            choices: ["53", "8", "a + b", "An error"],
            answer: 1, explain: "Python adds the values stored in a and b." },
          { type: "mc", prompt: "What does this output?",
            code: "x = 4\nx = x + 1\nprint(x)",
            choices: ["4", "5", "x + 1", "An error"],
            answer: 1, explain: "x = x + 1 takes the old value (4), adds 1, and stores it back." },
          { type: "arrange", prompt: "Build the code: increase score by 10",
            tokens: ["score", "=", "score", "+", "10"],
            answer: "score = score + 10", explain: "score = score + 10 (or score += 10)" },
          { type: "mc", prompt: "What is a shorter way to write <code>x = x + 1</code>?",
            choices: ["<code>x + 1</code>", "<code>x++</code>", "<code>x += 1</code>", "<code>x =+ 1</code>"],
            answer: 2, explain: "x += 1 adds 1 to x. (Python has no ++ operator!)" },
          { type: "mc", prompt: "What does this output?",
            code: 'first = "Py"\nsecond = "thon"\nprint(first + second)',
            choices: ["Py thon", "Python", "first + second", "An error"],
            answer: 1, explain: "+ joins (concatenates) two strings together." },
          { type: "type", prompt: "Swap shortcut: type the short form of  x = x + 5",
            answer: ["x += 5", "x+=5", "x +=5", "x+= 5"], explain: "x += 5" },
        ],
      },
    ],
  },
  {
    title: "Unit 3 · Strings & Numbers",
    subtitle: "text, math and types",
    color: "u-purple",
    lessons: [
      {
        title: "String skills",
        icon: "🧵",
        exercises: [
          { type: "mc", prompt: "What does this output?",
            code: 'name = "python"\nprint(name.upper())',
            choices: ["python", "PYTHON", "Python", "An error"],
            answer: 1, explain: ".upper() returns the string in ALL CAPS." },
          { type: "mc", prompt: "What does this output?",
            code: 'word = "hello"\nprint(len(word))',
            choices: ["4", "5", "hello", "An error"],
            answer: 1, explain: "len() counts the characters: h-e-l-l-o = 5." },
          { type: "mc", prompt: "What does this output?",
            code: 'word = "cat"\nprint(word[0])',
            choices: ["c", "a", "t", "cat"],
            answer: 0, explain: "Indexing starts at 0, so word[0] is the first letter." },
          { type: "arrange", prompt: "Build the code: print name in lowercase",
            tokens: ["print", "(", "name", ".", "lower", "(", ")", ")"],
            answer: "print ( name . lower ( ) )", explain: "print(name.lower())" },
          { type: "mc", prompt: "What does an f-string do?",
            code: 'age = 12\nprint(f"I am {age}")',
            choices: ["Prints: I am {age}", "Prints: I am 12", "Causes an error", "Prints: f I am 12"],
            answer: 1, explain: "f-strings replace {age} with the variable's value." },
          { type: "type", prompt: 'Use an f-string to print Hi {name} — type: print(f"Hi {name}")',
            answer: ['print(f"Hi {name}")', "print(f'Hi {name}')"], explain: 'print(f"Hi {name}")' },
        ],
      },
      {
        title: "Number crunching",
        icon: "🔢",
        exercises: [
          { type: "mc", prompt: "What does this output?",
            code: "print(7 // 2)",
            choices: ["3.5", "3", "4", "An error"],
            answer: 1, explain: "// is floor division — it rounds down to a whole number." },
          { type: "mc", prompt: "What does this output?",
            code: "print(7 % 2)",
            choices: ["3", "3.5", "1", "0"],
            answer: 2, explain: "% gives the remainder: 7 ÷ 2 = 3 remainder 1." },
          { type: "mc", prompt: "What does this output?",
            code: "print(2 ** 3)",
            choices: ["6", "8", "9", "23"],
            answer: 1, explain: "** is power: 2 ** 3 = 2 × 2 × 2 = 8." },
          { type: "mc", prompt: "Which value is a float?",
            choices: ["<code>7</code>", "<code>\"7\"</code>", "<code>7.0</code>", "<code>True</code>"],
            answer: 2, explain: "Numbers with a decimal point are floats." },
          { type: "mc", prompt: "What does this output?",
            code: 'print(int("5") + 5)',
            choices: ["55", "10", '"55"', "An error"],
            answer: 1, explain: 'int("5") converts the text "5" into the number 5.' },
          { type: "arrange", prompt: "Build the code: convert the text age into a number",
            tokens: ["age", "=", "int", "(", "age", ")"],
            answer: "age = int ( age )", explain: "age = int(age)" },
        ],
      },
    ],
  },
  {
    title: "Unit 4 · Conditionals",
    subtitle: "if, elif, else — making decisions",
    color: "u-gold",
    lessons: [
      {
        title: "if statements",
        icon: "🚦",
        exercises: [
          { type: "mc", prompt: "What does this output?",
            code: 'age = 15\nif age >= 13:\n    print("Teenager")',
            choices: ["Teenager", "Nothing", "age >= 13", "An error"],
            answer: 0, explain: "15 >= 13 is True, so the indented code runs." },
          { type: "mc", prompt: "Which symbol checks if two values are EQUAL?",
            choices: ["<code>=</code>", "<code>==</code>", "<code>=>=</code>", "<code>equals</code>"],
            answer: 1, explain: "== compares. A single = assigns." },
          { type: "mc", prompt: "What punctuation must end an if line?",
            code: "if score > 50",
            choices: ["A semicolon ;", "A period .", "A colon :", "Nothing"],
            answer: 2, explain: "if score > 50:  — the colon starts the indented block." },
          { type: "arrange", prompt: "Build the code: if x is greater than 10, print \"big\"",
            tokens: ["if", "x", ">", "10", ":", "print", "(", '"big"', ")"],
            answer: 'if x > 10 : print ( "big" )', explain: 'if x > 10: print("big")' },
          { type: "mc", prompt: "What does this output?",
            code: 'x = 5\nif x == 5:\n    print("five")\nelse:\n    print("not five")',
            choices: ["five", "not five", "Both", "Nothing"],
            answer: 0, explain: "x == 5 is True, so the if branch runs and else is skipped." },
          { type: "mc", prompt: "What does this output?",
            code: 'n = 0\nif n > 0:\n    print("positive")\nelif n < 0:\n    print("negative")\nelse:\n    print("zero")',
            choices: ["positive", "negative", "zero", "An error"],
            answer: 2, explain: "n is 0, so both conditions are False and else runs." },
        ],
      },
      {
        title: "Logic & comparison",
        icon: "🧠",
        exercises: [
          { type: "mc", prompt: "What is the value of this expression?",
            code: "10 > 3 and 2 > 5",
            choices: ["True", "False", "10", "An error"],
            answer: 1, explain: "and needs BOTH sides to be True. 2 > 5 is False." },
          { type: "mc", prompt: "What is the value of this expression?",
            code: "10 > 3 or 2 > 5",
            choices: ["True", "False", "Maybe", "An error"],
            answer: 0, explain: "or needs only ONE side to be True. 10 > 3 is True." },
          { type: "mc", prompt: "What does <code>not True</code> evaluate to?",
            choices: ["True", "False", "0", "An error"],
            answer: 1, explain: "not flips a boolean: not True → False." },
          { type: "mc", prompt: "Which checks that x is NOT equal to 3?",
            choices: ["<code>x =! 3</code>", "<code>x != 3</code>", "<code>x <> 3</code>", "<code>x not 3</code>"],
            answer: 1, explain: "!= means 'not equal to'." },
          { type: "arrange", prompt: "Build the condition: age is at least 13 AND age is under 20",
            tokens: ["age", ">=", "13", "and", "age", "<", "20"],
            answer: "age >= 13 and age < 20", explain: "age >= 13 and age < 20" },
          { type: "mc", prompt: "What does this output?",
            code: 'logged_in = True\nif not logged_in:\n    print("Please log in")\nelse:\n    print("Welcome!")',
            choices: ["Please log in", "Welcome!", "Nothing", "An error"],
            answer: 1, explain: "not True is False, so the else branch runs." },
        ],
      },
    ],
  },
  {
    title: "Unit 5 · Loops",
    subtitle: "for, while and range",
    color: "u-red",
    lessons: [
      {
        title: "for loops",
        icon: "🔁",
        exercises: [
          { type: "mc", prompt: "How many times does this print?",
            code: 'for i in range(3):\n    print("hi")',
            choices: ["2", "3", "4", "Forever"],
            answer: 1, explain: "range(3) gives 0, 1, 2 — three loops." },
          { type: "mc", prompt: "What does this output?",
            code: "for i in range(3):\n    print(i)",
            choices: ["1 2 3", "0 1 2", "0 1 2 3", "3 3 3"],
            answer: 1, explain: "range(3) starts at 0 and stops BEFORE 3." },
          { type: "arrange", prompt: "Build the code: loop 5 times",
            tokens: ["for", "i", "in", "range", "(", "5", ")", ":"],
            answer: "for i in range ( 5 ) :", explain: "for i in range(5):" },
          { type: "mc", prompt: "What does this output?",
            code: 'for letter in "abc":\n    print(letter)',
            choices: ["abc", "a b c (each on its own line)", "letter letter letter", "An error"],
            answer: 1, explain: "A for loop can walk through each character of a string." },
          { type: "mc", prompt: "What does range(2, 5) produce?",
            choices: ["2 3 4 5", "2 3 4", "3 4 5", "2 5"],
            answer: 1, explain: "range(start, stop) includes start but stops before stop." },
          { type: "type", prompt: "Type the first line of a loop over range(10) using variable i",
            answer: ["for i in range(10):", "for i in range(10) :"], explain: "for i in range(10):" },
        ],
      },
      {
        title: "while loops",
        icon: "⏳",
        exercises: [
          { type: "mc", prompt: "What does this output?",
            code: "n = 1\nwhile n <= 3:\n    print(n)\n    n += 1",
            choices: ["1 2 3", "1 2 3 4", "0 1 2 3", "Forever"],
            answer: 0, explain: "The loop runs while n <= 3, printing 1, 2, 3." },
          { type: "mc", prompt: "What's wrong with this loop?",
            code: 'n = 1\nwhile n <= 3:\n    print(n)',
            choices: ["Nothing", "It never runs", "It runs forever", "Syntax error"],
            answer: 2, explain: "n never changes, so n <= 3 stays True forever — an infinite loop!" },
          { type: "mc", prompt: "Which keyword exits a loop immediately?",
            choices: ["<code>stop</code>", "<code>exit</code>", "<code>break</code>", "<code>end</code>"],
            answer: 2, explain: "break jumps out of the loop right away." },
          { type: "mc", prompt: "Which keyword skips to the next loop iteration?",
            choices: ["<code>skip</code>", "<code>continue</code>", "<code>next</code>", "<code>pass</code>"],
            answer: 1, explain: "continue skips the rest of this iteration and moves on." },
          { type: "arrange", prompt: "Build the code: loop while lives is greater than 0",
            tokens: ["while", "lives", ">", "0", ":"],
            answer: "while lives > 0 :", explain: "while lives > 0:" },
          { type: "mc", prompt: "What does this output?",
            code: "total = 0\nfor i in range(4):\n    total += i\nprint(total)",
            choices: ["4", "6", "10", "0"],
            answer: 1, explain: "0 + 1 + 2 + 3 = 6." },
        ],
      },
    ],
  },
  {
    title: "Unit 6 · Lists & Functions",
    subtitle: "collections and reusable code",
    color: "u-teal",
    lessons: [
      {
        title: "Lists",
        icon: "📋",
        exercises: [
          { type: "mc", prompt: "Which creates a list of three fruits?",
            choices: ['<code>fruits = "apple, kiwi, plum"</code>', '<code>fruits = ["apple", "kiwi", "plum"]</code>', '<code>fruits = (apple, kiwi, plum)</code>', "<code>list fruits = 3</code>"],
            answer: 1, explain: "Lists use square brackets with items separated by commas." },
          { type: "mc", prompt: "What does this output?",
            code: 'pets = ["cat", "dog", "fish"]\nprint(pets[1])',
            choices: ["cat", "dog", "fish", "1"],
            answer: 1, explain: "Index 1 is the SECOND item — lists start at 0." },
          { type: "mc", prompt: "How do you add \"bird\" to the end of the pets list?",
            choices: ["<code>pets.add(\"bird\")</code>", "<code>pets.append(\"bird\")</code>", "<code>pets.push(\"bird\")</code>", "<code>pets + \"bird\"</code>"],
            answer: 1, explain: ".append() adds an item to the end of a list." },
          { type: "mc", prompt: "What does this output?",
            code: "nums = [4, 8, 15]\nprint(len(nums))",
            choices: ["3", "27", "15", "4"],
            answer: 0, explain: "len() returns how many items the list has." },
          { type: "arrange", prompt: "Build the code: loop through every pet in pets",
            tokens: ["for", "pet", "in", "pets", ":"],
            answer: "for pet in pets :", explain: "for pet in pets:" },
          { type: "mc", prompt: "What does this output?",
            code: "nums = [1, 2, 3]\nnums.append(4)\nprint(nums)",
            choices: ["[1, 2, 3]", "[1, 2, 3, 4]", "[4, 1, 2, 3]", "4"],
            answer: 1, explain: "append() puts 4 at the end of the list." },
        ],
      },
      {
        title: "Functions",
        icon: "⚙️",
        exercises: [
          { type: "mc", prompt: "Which keyword defines a function?",
            choices: ["<code>function</code>", "<code>def</code>", "<code>fun</code>", "<code>make</code>"],
            answer: 1, explain: "def starts a function definition." },
          { type: "arrange", prompt: "Build the code: define a function called greet",
            tokens: ["def", "greet", "(", ")", ":"],
            answer: "def greet ( ) :", explain: "def greet():" },
          { type: "mc", prompt: "What does this output?",
            code: 'def greet():\n    print("Hello!")\n\ngreet()\ngreet()',
            choices: ["Hello!", "Hello! Hello! (twice)", "Nothing", "An error"],
            answer: 1, explain: "The function is called twice, so it prints twice." },
          { type: "mc", prompt: "What does this output?",
            code: "def double(n):\n    return n * 2\n\nprint(double(6))",
            choices: ["6", "12", "n * 2", "double(6)"],
            answer: 1, explain: "double(6) returns 6 × 2 = 12, which is then printed." },
          { type: "mc", prompt: "What does <code>return</code> do?",
            choices: ["Prints a value", "Sends a value back to the caller and exits the function", "Restarts the function", "Deletes the function"],
            answer: 1, explain: "return hands a result back and ends the function." },
          { type: "type", prompt: "Call a function named party (no arguments)",
            answer: ["party()", "party ()"], explain: "party()" },
          { type: "mc", prompt: "What does this output?",
            code: 'def shout(word):\n    return word.upper() + "!"\n\nprint(shout("yay"))',
            choices: ["yay", "YAY!", "yay!", "WORD!"],
            answer: 1, explain: '"yay".upper() is "YAY", plus "!" makes "YAY!".' },
        ],
      },
    ],
  },
  {
    title: "Unit 7 · Dictionaries",
    subtitle: "key-value pairs",
    color: "",
    lessons: [
      {
        title: "Dictionary basics",
        icon: "📖",
        exercises: [
          { type: "mc", prompt: "Which creates a dictionary?",
            choices: ['<code>d = ["name", "Ana"]</code>', '<code>d = {"name": "Ana"}</code>', '<code>d = ("name", "Ana")</code>', '<code>d = "name: Ana"</code>'],
            answer: 1, explain: "Dictionaries use curly braces with key: value pairs." },
          { type: "mc", prompt: "What does this output?",
            code: 'person = {"name": "Ana", "age": 12}\nprint(person["name"])',
            choices: ["name", "Ana", "12", "An error"],
            answer: 1, explain: 'person["name"] looks up the value stored under the key "name".' },
          { type: "arrange", prompt: "Build the code: print the value stored under the key \"age\"",
            tokens: ["print", "(", "person", "[", '"age"', "]", ")"],
            answer: 'print ( person [ "age" ] )', explain: 'print(person["age"])' },
          { type: "mc", prompt: "How do you ADD a new key \"city\" with value \"Paris\"?",
            choices: ['<code>person.add("city", "Paris")</code>', '<code>person["city"] = "Paris"</code>', '<code>person.append("city": "Paris")</code>', '<code>person + "city"</code>'],
            answer: 1, explain: "Assigning to a new key adds it to the dictionary." },
          { type: "mc", prompt: "What does this output?",
            code: 'd = {"a": 1}\nd["a"] = 5\nprint(d["a"])',
            choices: ["1", "5", "1 5", "An error"],
            answer: 1, explain: "Assigning to an existing key replaces its value." },
          { type: "type", prompt: "Create an empty dictionary called data (use curly braces)",
            answer: ["data = {}", "data={}", "data = dict()", "data = { }"], explain: "data = {}" },
        ],
      },
      {
        title: "Dictionaries in action",
        icon: "🗂️",
        exercises: [
          { type: "mc", prompt: "What does this output?",
            code: 'd = {"a": 1, "b": 2}\nprint(len(d))',
            choices: ["1", "2", "3", "4"],
            answer: 1, explain: "len() counts the key-value pairs: a and b = 2." },
          { type: "mc", prompt: "How do you check if the key \"name\" exists in person?",
            choices: ['<code>person.has("name")</code>', '<code>"name" in person</code>', '<code>person.exists("name")</code>', '<code>"name" == person</code>'],
            answer: 1, explain: 'The in keyword checks if a key exists: "name" in person.' },
          { type: "mc", prompt: "What does this loop print?",
            code: 'd = {"x": 1, "y": 2}\nfor key in d:\n    print(key)',
            choices: ["1 then 2", "x then y", "x:1 then y:2", "An error"],
            answer: 1, explain: "Looping over a dictionary gives you its KEYS." },
          { type: "mc", prompt: "What does this output?",
            code: 'd = {"a": 1}\nprint(d.get("z"))',
            choices: ["An error", "None", "0", "z"],
            answer: 1, explain: ".get() returns None (instead of crashing) when the key is missing." },
          { type: "arrange", prompt: "Build the code: loop through every key in person",
            tokens: ["for", "key", "in", "person", ":"],
            answer: "for key in person :", explain: "for key in person:" },
          { type: "mc", prompt: "What does this output?",
            code: 'scores = {"sam": 10}\nscores["sam"] += 5\nprint(scores["sam"])',
            choices: ["10", "5", "15", "An error"],
            answer: 2, explain: "+= adds 5 to the value stored under \"sam\": 10 + 5 = 15." },
        ],
      },
    ],
  },
  {
    title: "Unit 8 · Tuples & Sets",
    subtitle: "more ways to store data",
    color: "u-blue",
    lessons: [
      {
        title: "Tuples",
        icon: "📍",
        exercises: [
          { type: "mc", prompt: "Which creates a tuple?",
            choices: ["<code>point = [3, 4]</code>", "<code>point = (3, 4)</code>", "<code>point = {3, 4}</code>", "<code>point = 3, 4, []</code>"],
            answer: 1, explain: "Tuples use round parentheses: (3, 4)." },
          { type: "mc", prompt: "What does this output?",
            code: "point = (3, 4)\nprint(point[0])",
            choices: ["3", "4", "(3, 4)", "An error"],
            answer: 0, explain: "Tuples are indexed from 0, just like lists." },
          { type: "mc", prompt: "What happens when this runs?",
            code: "point = (3, 4)\npoint[0] = 9",
            choices: ["point becomes (9, 4)", "point becomes (9, 9)", "An error — tuples can't be changed", "Nothing"],
            answer: 2, explain: "Tuples are immutable: once created, they cannot be modified." },
          { type: "arrange", prompt: "Build the code: unpack point into x and y",
            tokens: ["x", ",", "y", "=", "point"],
            answer: "x , y = point", explain: "x, y = point" },
          { type: "mc", prompt: "What does this output?",
            code: "t = (1, 2, 3)\nprint(len(t))",
            choices: ["1", "2", "3", "6"],
            answer: 2, explain: "The tuple has three items." },
          { type: "mc", prompt: "What is the main difference between a list and a tuple?",
            choices: ["Tuples are faster to type", "Lists can be changed, tuples cannot", "Tuples can only hold numbers", "There is no difference"],
            answer: 1, explain: "Lists are mutable (changeable); tuples are immutable." },
        ],
      },
      {
        title: "Sets",
        icon: "🎯",
        exercises: [
          { type: "mc", prompt: "Which creates a set of three numbers?",
            choices: ["<code>s = [1, 2, 3]</code>", "<code>s = (1, 2, 3)</code>", "<code>s = {1, 2, 3}</code>", '<code>s = "1, 2, 3"</code>'],
            answer: 2, explain: "Sets use curly braces with just values (no colons)." },
          { type: "mc", prompt: "What does this output?",
            code: "nums = {1, 2, 2, 3, 3, 3}\nprint(len(nums))",
            choices: ["6", "3", "2", "An error"],
            answer: 1, explain: "Sets automatically remove duplicates — only 1, 2, 3 remain." },
          { type: "mc", prompt: "How do you add 4 to the set nums?",
            choices: ["<code>nums.append(4)</code>", "<code>nums.add(4)</code>", "<code>nums.push(4)</code>", "<code>nums[3] = 4</code>"],
            answer: 1, explain: "Sets use .add() — .append() is for lists." },
          { type: "mc", prompt: "What does this output?",
            code: "print(2 in {1, 2, 3})",
            choices: ["True", "False", "2", "An error"],
            answer: 0, explain: "in checks membership — 2 is in the set, so True." },
          { type: "arrange", prompt: "Build the code: remove duplicates from items using set()",
            tokens: ["unique", "=", "set", "(", "items", ")"],
            answer: "unique = set ( items )", explain: "unique = set(items)" },
          { type: "mc", prompt: "Which TWO things are special about sets?",
            choices: ["Ordered and sorted", "No duplicates and no fixed order", "Only strings allowed", "Always empty"],
            answer: 1, explain: "Sets keep unique values and don't guarantee any order." },
        ],
      },
    ],
  },
  {
    title: "Unit 9 · Errors & Exceptions",
    subtitle: "when things go wrong",
    color: "u-purple",
    lessons: [
      {
        title: "try & except",
        icon: "🛟",
        exercises: [
          { type: "mc", prompt: "Which keyword starts a block of code that MIGHT fail?",
            choices: ["<code>attempt</code>", "<code>try</code>", "<code>catch</code>", "<code>test</code>"],
            answer: 1, explain: "try: runs the risky code; except: handles the failure." },
          { type: "mc", prompt: "What does this output?",
            code: 'try:\n    print(1 / 0)\nexcept ZeroDivisionError:\n    print("oops")',
            choices: ["An error crashes the program", "oops", "0", "1 / 0"],
            answer: 1, explain: "Dividing by zero raises an error, which except catches — so \"oops\" prints." },
          { type: "arrange", prompt: "Build the line: catch a ValueError",
            tokens: ["except", "ValueError", ":"],
            answer: "except ValueError :", explain: "except ValueError:" },
          { type: "mc", prompt: "What error does this raise?",
            code: 'int("abc")',
            choices: ["ZeroDivisionError", "ValueError", "NameError", "No error"],
            answer: 1, explain: '"abc" can\'t be converted to a number → ValueError.' },
          { type: "mc", prompt: "What does this output?",
            code: 'try:\n    x = 5 + 5\n    print(x)\nexcept:\n    print("error!")',
            choices: ["error!", "10", "10 then error!", "Nothing"],
            answer: 1, explain: "No error happens, so the except block is skipped." },
          { type: "type", prompt: "Type the keyword that CATCHES an error (comes after try)",
            answer: ["except"], explain: "except" },
        ],
      },
      {
        title: "Know your errors",
        icon: "🐛",
        exercises: [
          { type: "mc", prompt: "What causes a NameError?",
            choices: ["Dividing by zero", "Using a variable that was never defined", "A missing colon", "A wrong password"],
            answer: 1, explain: "NameError: name 'x' is not defined — the variable doesn't exist." },
          { type: "mc", prompt: "What error does this raise?",
            code: "nums = [1, 2]\nprint(nums[5])",
            choices: ["IndexError", "ValueError", "KeyError", "No error"],
            answer: 0, explain: "Index 5 doesn't exist in a 2-item list → IndexError." },
          { type: "mc", prompt: "What error does this raise?",
            code: '"1" + 1',
            choices: ["ValueError", "TypeError", "NameError", "No error — it prints 2"],
            answer: 1, explain: "You can't add a string and a number → TypeError." },
          { type: "mc", prompt: "Why is this a SyntaxError?",
            code: 'if x > 5\n    print("big")',
            choices: ["print is misspelled", "The if line is missing a colon :", "x is undefined", "Wrong indentation"],
            answer: 1, explain: "Every if line must end with a colon." },
          { type: "mc", prompt: "What error does this raise?",
            code: 'd = {"a": 1}\nprint(d["b"])',
            choices: ["IndexError", "KeyError", "ValueError", "No error"],
            answer: 1, explain: 'The key "b" doesn\'t exist in the dictionary → KeyError.' },
          { type: "mc", prompt: "When does a <code>finally</code> block run?",
            choices: ["Only when there's an error", "Only when there's NO error", "Always, error or not", "Never"],
            answer: 2, explain: "finally always runs — perfect for cleanup." },
        ],
      },
    ],
  },
  {
    title: "Unit 10 · Classes & Objects",
    subtitle: "build your own types",
    color: "u-gold",
    lessons: [
      {
        title: "Classes 101",
        icon: "🏗️",
        exercises: [
          { type: "mc", prompt: "Which keyword defines a class?",
            choices: ["<code>def</code>", "<code>class</code>", "<code>object</code>", "<code>type</code>"],
            answer: 1, explain: "class starts a class definition." },
          { type: "arrange", prompt: "Build the code: define a class called Dog",
            tokens: ["class", "Dog", ":"],
            answer: "class Dog :", explain: "class Dog:" },
          { type: "mc", prompt: "When does <code>__init__</code> run?",
            choices: ["When the program starts", "Every time you create a new object", "Only once ever", "When the object is deleted"],
            answer: 1, explain: "__init__ is the constructor — it sets up each new object." },
          { type: "mc", prompt: "What is <code>self</code>?",
            choices: ["A special string", "The object the method is working on", "The class name", "A Python error"],
            answer: 1, explain: "self refers to the specific object — each dog is its own self." },
          { type: "mc", prompt: "What does this output?",
            code: 'class Dog:\n    def bark(self):\n        print("Woof!")\n\nd = Dog()\nd.bark()',
            choices: ["Woof!", "bark", "Nothing", "An error"],
            answer: 0, explain: "d = Dog() creates the object, d.bark() calls its method." },
          { type: "mc", prompt: "How do you CREATE a Dog object?",
            choices: ["<code>d = new Dog</code>", "<code>d = Dog()</code>", "<code>d = create Dog</code>", "<code>Dog(d)</code>"],
            answer: 1, explain: "Calling the class like a function creates an object (no 'new' keyword in Python)." },
        ],
      },
      {
        title: "Objects & attributes",
        icon: "🧬",
        exercises: [
          { type: "mc", prompt: "What does this output?",
            code: 'class Dog:\n    def __init__(self, name):\n        self.name = name\n\nd = Dog("Rex")\nprint(d.name)',
            choices: ["name", "Rex", "self.name", "An error"],
            answer: 1, explain: "__init__ stores \"Rex\" in the object's name attribute." },
          { type: "arrange", prompt: "Build the line: store name on the object (inside __init__)",
            tokens: ["self", ".", "name", "=", "name"],
            answer: "self . name = name", explain: "self.name = name" },
          { type: "mc", prompt: "How do you call the bark method on object d?",
            choices: ["<code>bark(d)</code>", "<code>d.bark()</code>", "<code>call d.bark</code>", "<code>Dog.bark</code>"],
            answer: 1, explain: "Methods are called with a dot: object.method()." },
          { type: "mc", prompt: "What does this output?",
            code: 'class Cat:\n    def __init__(self, name):\n        self.name = name\n\na = Cat("Momo")\nb = Cat("Luna")\nprint(b.name)',
            choices: ["Momo", "Luna", "Momo Luna", "An error"],
            answer: 1, explain: "Each object keeps its own attributes — b's name is Luna." },
          { type: "type", prompt: "Create a Cat object and store it in a variable called c",
            answer: ["c = Cat()", "c=Cat()", "c = Cat ()"], explain: "c = Cat()" },
          { type: "mc", prompt: "What is the difference between a function and a method?",
            choices: ["Nothing", "A method belongs to a class and is called on an object", "Methods are faster", "Functions can't return values"],
            answer: 1, explain: "A method is a function defined inside a class — you call it on objects." },
        ],
      },
    ],
  },
  {
    title: "Unit 11 · Power Python",
    subtitle: "modules and comprehensions",
    color: "u-red",
    lessons: [
      {
        title: "Imports & modules",
        icon: "📦",
        exercises: [
          { type: "mc", prompt: "Which keyword lets you use code from another module?",
            choices: ["<code>include</code>", "<code>import</code>", "<code>require</code>", "<code>using</code>"],
            answer: 1, explain: "import math brings in the math module." },
          { type: "mc", prompt: "What does this output?",
            code: "import math\nprint(math.sqrt(16))",
            choices: ["4.0", "8", "256", "An error"],
            answer: 0, explain: "sqrt finds the square root: √16 = 4.0 (a float)." },
          { type: "arrange", prompt: "Build the code: import only randint from the random module",
            tokens: ["from", "random", "import", "randint"],
            answer: "from random import randint", explain: "from random import randint" },
          { type: "mc", prompt: "What does <code>random.randint(1, 6)</code> return?",
            choices: ["Always 1", "Always 6", "A random whole number from 1 to 6", "A random decimal"],
            answer: 2, explain: "randint(1, 6) — like rolling a die. Both ends are included." },
          { type: "type", prompt: "Type the code to import the math module",
            answer: ["import math"], explain: "import math" },
          { type: "mc", prompt: "What does this output?",
            code: "import math\nprint(math.floor(3.9))",
            choices: ["4", "3", "3.9", "An error"],
            answer: 1, explain: "floor() always rounds DOWN: 3.9 → 3." },
        ],
      },
      {
        title: "List comprehensions",
        icon: "✨",
        exercises: [
          { type: "mc", prompt: "What does this output?",
            code: "print([x * 2 for x in [1, 2, 3]])",
            choices: ["[1, 2, 3]", "[2, 4, 6]", "[1, 2, 3, 1, 2, 3]", "6"],
            answer: 1, explain: "Each item is doubled: [2, 4, 6]." },
          { type: "mc", prompt: "What list does this create?",
            code: "[x for x in range(3)]",
            choices: ["[1, 2, 3]", "[0, 1, 2]", "[3]", "[0, 1, 2, 3]"],
            answer: 1, explain: "range(3) gives 0, 1, 2." },
          { type: "arrange", prompt: "Build the code: make a list of squares from nums",
            tokens: ["squares", "=", "[", "x", "*", "x", "for", "x", "in", "nums", "]"],
            answer: "squares = [ x * x for x in nums ]", explain: "squares = [x * x for x in nums]" },
          { type: "mc", prompt: "What does this output?",
            code: "print([x for x in range(10) if x % 2 == 0])",
            choices: ["[1, 3, 5, 7, 9]", "[0, 2, 4, 6, 8]", "[2, 4, 6, 8, 10]", "[0, 1, 2, 3, 4]"],
            answer: 1, explain: "The if keeps only even numbers (x % 2 == 0)." },
          { type: "mc", prompt: "What does this output?",
            code: 'print(len([c for c in "hello"]))',
            choices: ["1", "4", "5", "An error"],
            answer: 2, explain: "One list item per character: h-e-l-l-o = 5." },
          { type: "mc", prompt: "A list comprehension is a short way to…",
            choices: ["Delete a list", "Build a new list with a loop in one line", "Sort a list", "Import a list"],
            answer: 1, explain: "It squeezes a for loop that builds a list into a single line." },
        ],
      },
    ],
  },
];
