"""Monthly job: fetch live phishing samples and write js/data/feed_latest.js.

Run by .github/workflows/monthly-feed.yml (and runnable manually). The generated
file provides a fresh phishing snapshot for the STATIC (no-server) demo, so the
"Pull latest phishing scams" button has real data even on GitHub Pages.
"""
import datetime
import json
import os
import sys

# Make the parent package importable (feed_fetch.py lives one level up).
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
import feed_fetch  # noqa: E402

OUT = os.path.join(ROOT, "js", "data", "feed_latest.js")


def main():
    count = int(os.environ.get("FEED_COUNT", "20"))
    try:
        samples, source = feed_fetch.fetch_samples(count)
    except Exception as e:
        # Transient feed/network problem: keep the existing snapshot, don't fail CI.
        print("Feed fetch failed (%s); keeping previous snapshot." % e)
        return 0

    snapshot = {
        "generated_at": datetime.date.today().isoformat(),
        "source": source,
        "count": len(samples),
        "samples": samples,
    }
    js = (
        "/* Auto-generated by scripts/fetch_feed.py via GitHub Action. Do not edit by hand. */\n"
        "window.TL = window.TL || {};\n"
        "TL.feedSnapshot = " + json.dumps(snapshot, indent=2) + ";\n"
    )
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(js)
    print("Wrote %d samples (source: %s) to %s" % (len(samples), source, OUT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
